package net.newbiz.ebil.billing.dao.model;

import java.util.Date;

public class MFeePlan extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fee_plan.fee_plan_cd
     *
     * @mbggenerated
     */
    private String feePlanCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fee_plan.fee_plan_nm
     *
     * @mbggenerated
     */
    private String feePlanNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fee_plan.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fee_plan.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fee_plan.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_fee_plan.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fee_plan.fee_plan_cd
     *
     * @return the value of m_fee_plan.fee_plan_cd
     *
     * @mbggenerated
     */
    public String getFeePlanCd() {
        return feePlanCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fee_plan.fee_plan_cd
     *
     * @param feePlanCd the value for m_fee_plan.fee_plan_cd
     *
     * @mbggenerated
     */
    public void setFeePlanCd(String feePlanCd) {
        this.feePlanCd = feePlanCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fee_plan.fee_plan_nm
     *
     * @return the value of m_fee_plan.fee_plan_nm
     *
     * @mbggenerated
     */
    public String getFeePlanNm() {
        return feePlanNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fee_plan.fee_plan_nm
     *
     * @param feePlanNm the value for m_fee_plan.fee_plan_nm
     *
     * @mbggenerated
     */
    public void setFeePlanNm(String feePlanNm) {
        this.feePlanNm = feePlanNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fee_plan.creater
     *
     * @return the value of m_fee_plan.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fee_plan.creater
     *
     * @param creater the value for m_fee_plan.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fee_plan.create_timestamp
     *
     * @return the value of m_fee_plan.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fee_plan.create_timestamp
     *
     * @param createTimestamp the value for m_fee_plan.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fee_plan.updater
     *
     * @return the value of m_fee_plan.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fee_plan.updater
     *
     * @param updater the value for m_fee_plan.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_fee_plan.update_timestamp
     *
     * @return the value of m_fee_plan.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_fee_plan.update_timestamp
     *
     * @param updateTimestamp the value for m_fee_plan.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}