package net.newbiz.ebil.billing.dao.model;

import java.util.Date;

public class MUnitCd extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.unit_cd
     *
     * @mbggenerated
     */
    private String unitCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.fee_plan_cd
     *
     * @mbggenerated
     */
    private String feePlanCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.unit_nm
     *
     * @mbggenerated
     */
    private String unitNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.calc_way
     *
     * @mbggenerated
     */
    private Short calcWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_unit_cd.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.unit_cd
     *
     * @return the value of m_unit_cd.unit_cd
     *
     * @mbggenerated
     */
    public String getUnitCd() {
        return unitCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.unit_cd
     *
     * @param unitCd the value for m_unit_cd.unit_cd
     *
     * @mbggenerated
     */
    public void setUnitCd(String unitCd) {
        this.unitCd = unitCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.fee_plan_cd
     *
     * @return the value of m_unit_cd.fee_plan_cd
     *
     * @mbggenerated
     */
    public String getFeePlanCd() {
        return feePlanCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.fee_plan_cd
     *
     * @param feePlanCd the value for m_unit_cd.fee_plan_cd
     *
     * @mbggenerated
     */
    public void setFeePlanCd(String feePlanCd) {
        this.feePlanCd = feePlanCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.unit_nm
     *
     * @return the value of m_unit_cd.unit_nm
     *
     * @mbggenerated
     */
    public String getUnitNm() {
        return unitNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.unit_nm
     *
     * @param unitNm the value for m_unit_cd.unit_nm
     *
     * @mbggenerated
     */
    public void setUnitNm(String unitNm) {
        this.unitNm = unitNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.calc_way
     *
     * @return the value of m_unit_cd.calc_way
     *
     * @mbggenerated
     */
    public Short getCalcWay() {
        return calcWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.calc_way
     *
     * @param calcWay the value for m_unit_cd.calc_way
     *
     * @mbggenerated
     */
    public void setCalcWay(Short calcWay) {
        this.calcWay = calcWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.creater
     *
     * @return the value of m_unit_cd.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.creater
     *
     * @param creater the value for m_unit_cd.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.create_timestamp
     *
     * @return the value of m_unit_cd.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.create_timestamp
     *
     * @param createTimestamp the value for m_unit_cd.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.updater
     *
     * @return the value of m_unit_cd.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.updater
     *
     * @param updater the value for m_unit_cd.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_unit_cd.update_timestamp
     *
     * @return the value of m_unit_cd.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_unit_cd.update_timestamp
     *
     * @param updateTimestamp the value for m_unit_cd.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}