package net.newbiz.ebil.billing.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class TBillDtl extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.bill_dtl_no
     *
     * @mbggenerated
     */
    private Long billDtlNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.bill_no
     *
     * @mbggenerated
     */
    private Long billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.unit_cd
     *
     * @mbggenerated
     */
    private String unitCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.calc_unit_amount
     *
     * @mbggenerated
     */
    private BigDecimal calcUnitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.unit_amount
     *
     * @mbggenerated
     */
    private BigDecimal unitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.tax
     *
     * @mbggenerated
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.tax_rate
     *
     * @mbggenerated
     */
    private BigDecimal taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_dtl.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.bill_dtl_no
     *
     * @return the value of t_bill_dtl.bill_dtl_no
     *
     * @mbggenerated
     */
    public Long getBillDtlNo() {
        return billDtlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.bill_dtl_no
     *
     * @param billDtlNo the value for t_bill_dtl.bill_dtl_no
     *
     * @mbggenerated
     */
    public void setBillDtlNo(Long billDtlNo) {
        this.billDtlNo = billDtlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.bill_no
     *
     * @return the value of t_bill_dtl.bill_no
     *
     * @mbggenerated
     */
    public Long getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.bill_no
     *
     * @param billNo the value for t_bill_dtl.bill_no
     *
     * @mbggenerated
     */
    public void setBillNo(Long billNo) {
        this.billNo = billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.unit_cd
     *
     * @return the value of t_bill_dtl.unit_cd
     *
     * @mbggenerated
     */
    public String getUnitCd() {
        return unitCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.unit_cd
     *
     * @param unitCd the value for t_bill_dtl.unit_cd
     *
     * @mbggenerated
     */
    public void setUnitCd(String unitCd) {
        this.unitCd = unitCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.calc_unit_amount
     *
     * @return the value of t_bill_dtl.calc_unit_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCalcUnitAmount() {
        return calcUnitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.calc_unit_amount
     *
     * @param calcUnitAmount the value for t_bill_dtl.calc_unit_amount
     *
     * @mbggenerated
     */
    public void setCalcUnitAmount(BigDecimal calcUnitAmount) {
        this.calcUnitAmount = calcUnitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.unit_amount
     *
     * @return the value of t_bill_dtl.unit_amount
     *
     * @mbggenerated
     */
    public BigDecimal getUnitAmount() {
        return unitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.unit_amount
     *
     * @param unitAmount the value for t_bill_dtl.unit_amount
     *
     * @mbggenerated
     */
    public void setUnitAmount(BigDecimal unitAmount) {
        this.unitAmount = unitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.fee
     *
     * @return the value of t_bill_dtl.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.fee
     *
     * @param fee the value for t_bill_dtl.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.tax
     *
     * @return the value of t_bill_dtl.tax
     *
     * @mbggenerated
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.tax
     *
     * @param tax the value for t_bill_dtl.tax
     *
     * @mbggenerated
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.tax_rate
     *
     * @return the value of t_bill_dtl.tax_rate
     *
     * @mbggenerated
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.tax_rate
     *
     * @param taxRate the value for t_bill_dtl.tax_rate
     *
     * @mbggenerated
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.memo
     *
     * @return the value of t_bill_dtl.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.memo
     *
     * @param memo the value for t_bill_dtl.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.creater
     *
     * @return the value of t_bill_dtl.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.creater
     *
     * @param creater the value for t_bill_dtl.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.create_timestamp
     *
     * @return the value of t_bill_dtl.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.create_timestamp
     *
     * @param createTimestamp the value for t_bill_dtl.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.updater
     *
     * @return the value of t_bill_dtl.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.updater
     *
     * @param updater the value for t_bill_dtl.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_dtl.update_timestamp
     *
     * @return the value of t_bill_dtl.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_dtl.update_timestamp
     *
     * @param updateTimestamp the value for t_bill_dtl.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}