package net.newbiz.ebil.billing.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TChgRsvExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public TChgRsvExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChgRsvNoIsNull() {
            addCriterion("chg_rsv_no is null");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoIsNotNull() {
            addCriterion("chg_rsv_no is not null");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoEqualTo(Long value) {
            addCriterion("chg_rsv_no =", value, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoNotEqualTo(Long value) {
            addCriterion("chg_rsv_no <>", value, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoGreaterThan(Long value) {
            addCriterion("chg_rsv_no >", value, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoGreaterThanOrEqualTo(Long value) {
            addCriterion("chg_rsv_no >=", value, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoLessThan(Long value) {
            addCriterion("chg_rsv_no <", value, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoLessThanOrEqualTo(Long value) {
            addCriterion("chg_rsv_no <=", value, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoIn(List<Long> values) {
            addCriterion("chg_rsv_no in", values, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoNotIn(List<Long> values) {
            addCriterion("chg_rsv_no not in", values, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoBetween(Long value1, Long value2) {
            addCriterion("chg_rsv_no between", value1, value2, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgRsvNoNotBetween(Long value1, Long value2) {
            addCriterion("chg_rsv_no not between", value1, value2, "chgRsvNo");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateIsNull() {
            addCriterion("chg_schedule_date is null");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateIsNotNull() {
            addCriterion("chg_schedule_date is not null");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateEqualTo(String value) {
            addCriterion("chg_schedule_date =", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateNotEqualTo(String value) {
            addCriterion("chg_schedule_date <>", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateGreaterThan(String value) {
            addCriterion("chg_schedule_date >", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateGreaterThanOrEqualTo(String value) {
            addCriterion("chg_schedule_date >=", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateLessThan(String value) {
            addCriterion("chg_schedule_date <", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateLessThanOrEqualTo(String value) {
            addCriterion("chg_schedule_date <=", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateLike(String value) {
            addCriterion("chg_schedule_date like", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateNotLike(String value) {
            addCriterion("chg_schedule_date not like", value, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateIn(List<String> values) {
            addCriterion("chg_schedule_date in", values, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateNotIn(List<String> values) {
            addCriterion("chg_schedule_date not in", values, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateBetween(String value1, String value2) {
            addCriterion("chg_schedule_date between", value1, value2, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgScheduleDateNotBetween(String value1, String value2) {
            addCriterion("chg_schedule_date not between", value1, value2, "chgScheduleDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateIsNull() {
            addCriterion("chg_apply_date is null");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateIsNotNull() {
            addCriterion("chg_apply_date is not null");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateEqualTo(String value) {
            addCriterion("chg_apply_date =", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateNotEqualTo(String value) {
            addCriterion("chg_apply_date <>", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateGreaterThan(String value) {
            addCriterion("chg_apply_date >", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateGreaterThanOrEqualTo(String value) {
            addCriterion("chg_apply_date >=", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateLessThan(String value) {
            addCriterion("chg_apply_date <", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateLessThanOrEqualTo(String value) {
            addCriterion("chg_apply_date <=", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateLike(String value) {
            addCriterion("chg_apply_date like", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateNotLike(String value) {
            addCriterion("chg_apply_date not like", value, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateIn(List<String> values) {
            addCriterion("chg_apply_date in", values, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateNotIn(List<String> values) {
            addCriterion("chg_apply_date not in", values, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateBetween(String value1, String value2) {
            addCriterion("chg_apply_date between", value1, value2, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyDateNotBetween(String value1, String value2) {
            addCriterion("chg_apply_date not between", value1, value2, "chgApplyDate");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContIsNull() {
            addCriterion("chg_apply_err_cont is null");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContIsNotNull() {
            addCriterion("chg_apply_err_cont is not null");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContEqualTo(String value) {
            addCriterion("chg_apply_err_cont =", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContNotEqualTo(String value) {
            addCriterion("chg_apply_err_cont <>", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContGreaterThan(String value) {
            addCriterion("chg_apply_err_cont >", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContGreaterThanOrEqualTo(String value) {
            addCriterion("chg_apply_err_cont >=", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContLessThan(String value) {
            addCriterion("chg_apply_err_cont <", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContLessThanOrEqualTo(String value) {
            addCriterion("chg_apply_err_cont <=", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContLike(String value) {
            addCriterion("chg_apply_err_cont like", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContNotLike(String value) {
            addCriterion("chg_apply_err_cont not like", value, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContIn(List<String> values) {
            addCriterion("chg_apply_err_cont in", values, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContNotIn(List<String> values) {
            addCriterion("chg_apply_err_cont not in", values, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContBetween(String value1, String value2) {
            addCriterion("chg_apply_err_cont between", value1, value2, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgApplyErrContNotBetween(String value1, String value2) {
            addCriterion("chg_apply_err_cont not between", value1, value2, "chgApplyErrCont");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeIsNull() {
            addCriterion("chg_tgt_type is null");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeIsNotNull() {
            addCriterion("chg_tgt_type is not null");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeEqualTo(Short value) {
            addCriterion("chg_tgt_type =", value, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeNotEqualTo(Short value) {
            addCriterion("chg_tgt_type <>", value, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeGreaterThan(Short value) {
            addCriterion("chg_tgt_type >", value, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("chg_tgt_type >=", value, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeLessThan(Short value) {
            addCriterion("chg_tgt_type <", value, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeLessThanOrEqualTo(Short value) {
            addCriterion("chg_tgt_type <=", value, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeIn(List<Short> values) {
            addCriterion("chg_tgt_type in", values, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeNotIn(List<Short> values) {
            addCriterion("chg_tgt_type not in", values, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeBetween(Short value1, Short value2) {
            addCriterion("chg_tgt_type between", value1, value2, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgTgtTypeNotBetween(Short value1, Short value2) {
            addCriterion("chg_tgt_type not between", value1, value2, "chgTgtType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeIsNull() {
            addCriterion("chg_way_type is null");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeIsNotNull() {
            addCriterion("chg_way_type is not null");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeEqualTo(Short value) {
            addCriterion("chg_way_type =", value, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeNotEqualTo(Short value) {
            addCriterion("chg_way_type <>", value, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeGreaterThan(Short value) {
            addCriterion("chg_way_type >", value, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("chg_way_type >=", value, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeLessThan(Short value) {
            addCriterion("chg_way_type <", value, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeLessThanOrEqualTo(Short value) {
            addCriterion("chg_way_type <=", value, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeIn(List<Short> values) {
            addCriterion("chg_way_type in", values, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeNotIn(List<Short> values) {
            addCriterion("chg_way_type not in", values, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeBetween(Short value1, Short value2) {
            addCriterion("chg_way_type between", value1, value2, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgWayTypeNotBetween(Short value1, Short value2) {
            addCriterion("chg_way_type not between", value1, value2, "chgWayType");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1IsNull() {
            addCriterion("chg_data_str_pkey1 is null");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1IsNotNull() {
            addCriterion("chg_data_str_pkey1 is not null");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1EqualTo(Long value) {
            addCriterion("chg_data_str_pkey1 =", value, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1NotEqualTo(Long value) {
            addCriterion("chg_data_str_pkey1 <>", value, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1GreaterThan(Long value) {
            addCriterion("chg_data_str_pkey1 >", value, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1GreaterThanOrEqualTo(Long value) {
            addCriterion("chg_data_str_pkey1 >=", value, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1LessThan(Long value) {
            addCriterion("chg_data_str_pkey1 <", value, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1LessThanOrEqualTo(Long value) {
            addCriterion("chg_data_str_pkey1 <=", value, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1In(List<Long> values) {
            addCriterion("chg_data_str_pkey1 in", values, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1NotIn(List<Long> values) {
            addCriterion("chg_data_str_pkey1 not in", values, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1Between(Long value1, Long value2) {
            addCriterion("chg_data_str_pkey1 between", value1, value2, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey1NotBetween(Long value1, Long value2) {
            addCriterion("chg_data_str_pkey1 not between", value1, value2, "chgDataStrPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2IsNull() {
            addCriterion("chg_data_str_pkey2 is null");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2IsNotNull() {
            addCriterion("chg_data_str_pkey2 is not null");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2EqualTo(Long value) {
            addCriterion("chg_data_str_pkey2 =", value, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2NotEqualTo(Long value) {
            addCriterion("chg_data_str_pkey2 <>", value, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2GreaterThan(Long value) {
            addCriterion("chg_data_str_pkey2 >", value, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2GreaterThanOrEqualTo(Long value) {
            addCriterion("chg_data_str_pkey2 >=", value, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2LessThan(Long value) {
            addCriterion("chg_data_str_pkey2 <", value, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2LessThanOrEqualTo(Long value) {
            addCriterion("chg_data_str_pkey2 <=", value, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2In(List<Long> values) {
            addCriterion("chg_data_str_pkey2 in", values, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2NotIn(List<Long> values) {
            addCriterion("chg_data_str_pkey2 not in", values, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2Between(Long value1, Long value2) {
            addCriterion("chg_data_str_pkey2 between", value1, value2, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey2NotBetween(Long value1, Long value2) {
            addCriterion("chg_data_str_pkey2 not between", value1, value2, "chgDataStrPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3IsNull() {
            addCriterion("chg_data_str_pkey3 is null");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3IsNotNull() {
            addCriterion("chg_data_str_pkey3 is not null");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3EqualTo(Long value) {
            addCriterion("chg_data_str_pkey3 =", value, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3NotEqualTo(Long value) {
            addCriterion("chg_data_str_pkey3 <>", value, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3GreaterThan(Long value) {
            addCriterion("chg_data_str_pkey3 >", value, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3GreaterThanOrEqualTo(Long value) {
            addCriterion("chg_data_str_pkey3 >=", value, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3LessThan(Long value) {
            addCriterion("chg_data_str_pkey3 <", value, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3LessThanOrEqualTo(Long value) {
            addCriterion("chg_data_str_pkey3 <=", value, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3In(List<Long> values) {
            addCriterion("chg_data_str_pkey3 in", values, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3NotIn(List<Long> values) {
            addCriterion("chg_data_str_pkey3 not in", values, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3Between(Long value1, Long value2) {
            addCriterion("chg_data_str_pkey3 between", value1, value2, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataStrPkey3NotBetween(Long value1, Long value2) {
            addCriterion("chg_data_str_pkey3 not between", value1, value2, "chgDataStrPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1IsNull() {
            addCriterion("chg_data_apply_pkey1 is null");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1IsNotNull() {
            addCriterion("chg_data_apply_pkey1 is not null");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1EqualTo(Long value) {
            addCriterion("chg_data_apply_pkey1 =", value, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1NotEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey1 <>", value, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1GreaterThan(Long value) {
            addCriterion("chg_data_apply_pkey1 >", value, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1GreaterThanOrEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey1 >=", value, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1LessThan(Long value) {
            addCriterion("chg_data_apply_pkey1 <", value, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1LessThanOrEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey1 <=", value, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1In(List<Long> values) {
            addCriterion("chg_data_apply_pkey1 in", values, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1NotIn(List<Long> values) {
            addCriterion("chg_data_apply_pkey1 not in", values, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1Between(Long value1, Long value2) {
            addCriterion("chg_data_apply_pkey1 between", value1, value2, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey1NotBetween(Long value1, Long value2) {
            addCriterion("chg_data_apply_pkey1 not between", value1, value2, "chgDataApplyPkey1");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2IsNull() {
            addCriterion("chg_data_apply_pkey2 is null");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2IsNotNull() {
            addCriterion("chg_data_apply_pkey2 is not null");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2EqualTo(Long value) {
            addCriterion("chg_data_apply_pkey2 =", value, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2NotEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey2 <>", value, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2GreaterThan(Long value) {
            addCriterion("chg_data_apply_pkey2 >", value, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2GreaterThanOrEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey2 >=", value, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2LessThan(Long value) {
            addCriterion("chg_data_apply_pkey2 <", value, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2LessThanOrEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey2 <=", value, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2In(List<Long> values) {
            addCriterion("chg_data_apply_pkey2 in", values, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2NotIn(List<Long> values) {
            addCriterion("chg_data_apply_pkey2 not in", values, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2Between(Long value1, Long value2) {
            addCriterion("chg_data_apply_pkey2 between", value1, value2, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey2NotBetween(Long value1, Long value2) {
            addCriterion("chg_data_apply_pkey2 not between", value1, value2, "chgDataApplyPkey2");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3IsNull() {
            addCriterion("chg_data_apply_pkey3 is null");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3IsNotNull() {
            addCriterion("chg_data_apply_pkey3 is not null");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3EqualTo(Long value) {
            addCriterion("chg_data_apply_pkey3 =", value, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3NotEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey3 <>", value, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3GreaterThan(Long value) {
            addCriterion("chg_data_apply_pkey3 >", value, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3GreaterThanOrEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey3 >=", value, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3LessThan(Long value) {
            addCriterion("chg_data_apply_pkey3 <", value, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3LessThanOrEqualTo(Long value) {
            addCriterion("chg_data_apply_pkey3 <=", value, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3In(List<Long> values) {
            addCriterion("chg_data_apply_pkey3 in", values, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3NotIn(List<Long> values) {
            addCriterion("chg_data_apply_pkey3 not in", values, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3Between(Long value1, Long value2) {
            addCriterion("chg_data_apply_pkey3 between", value1, value2, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andChgDataApplyPkey3NotBetween(Long value1, Long value2) {
            addCriterion("chg_data_apply_pkey3 not between", value1, value2, "chgDataApplyPkey3");
            return (Criteria) this;
        }

        public Criteria andSysStateCdIsNull() {
            addCriterion("sys_state_cd is null");
            return (Criteria) this;
        }

        public Criteria andSysStateCdIsNotNull() {
            addCriterion("sys_state_cd is not null");
            return (Criteria) this;
        }

        public Criteria andSysStateCdEqualTo(Short value) {
            addCriterion("sys_state_cd =", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdNotEqualTo(Short value) {
            addCriterion("sys_state_cd <>", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdGreaterThan(Short value) {
            addCriterion("sys_state_cd >", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdGreaterThanOrEqualTo(Short value) {
            addCriterion("sys_state_cd >=", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdLessThan(Short value) {
            addCriterion("sys_state_cd <", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdLessThanOrEqualTo(Short value) {
            addCriterion("sys_state_cd <=", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdIn(List<Short> values) {
            addCriterion("sys_state_cd in", values, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdNotIn(List<Short> values) {
            addCriterion("sys_state_cd not in", values, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdBetween(Short value1, Short value2) {
            addCriterion("sys_state_cd between", value1, value2, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdNotBetween(Short value1, Short value2) {
            addCriterion("sys_state_cd not between", value1, value2, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_chg_rsv
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}