package net.newbiz.ebil.billing.dao.model;

import java.util.Date;

public class TCustLink extends TCustLinkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_link.cust_link_type
     *
     * @mbggenerated
     */
    private Short custLinkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_link.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_link.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_link.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_link.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_link.cust_link_type
     *
     * @return the value of t_cust_link.cust_link_type
     *
     * @mbggenerated
     */
    public Short getCustLinkType() {
        return custLinkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_link.cust_link_type
     *
     * @param custLinkType the value for t_cust_link.cust_link_type
     *
     * @mbggenerated
     */
    public void setCustLinkType(Short custLinkType) {
        this.custLinkType = custLinkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_link.creater
     *
     * @return the value of t_cust_link.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_link.creater
     *
     * @param creater the value for t_cust_link.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_link.create_timestamp
     *
     * @return the value of t_cust_link.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_link.create_timestamp
     *
     * @param createTimestamp the value for t_cust_link.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_link.updater
     *
     * @return the value of t_cust_link.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_link.updater
     *
     * @param updater the value for t_cust_link.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_link.update_timestamp
     *
     * @return the value of t_cust_link.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_link.update_timestamp
     *
     * @param updateTimestamp the value for t_cust_link.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}