package net.newbiz.ebil.billing.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCustAddrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public TCustAddrExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustCdIsNull() {
            addCriterion("cust_cd is null");
            return (Criteria) this;
        }

        public Criteria andCustCdIsNotNull() {
            addCriterion("cust_cd is not null");
            return (Criteria) this;
        }

        public Criteria andCustCdEqualTo(Integer value) {
            addCriterion("cust_cd =", value, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdNotEqualTo(Integer value) {
            addCriterion("cust_cd <>", value, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdGreaterThan(Integer value) {
            addCriterion("cust_cd >", value, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_cd >=", value, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdLessThan(Integer value) {
            addCriterion("cust_cd <", value, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_cd <=", value, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdIn(List<Integer> values) {
            addCriterion("cust_cd in", values, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdNotIn(List<Integer> values) {
            addCriterion("cust_cd not in", values, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdBetween(Integer value1, Integer value2) {
            addCriterion("cust_cd between", value1, value2, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustCdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_cd not between", value1, value2, "custCd");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqIsNull() {
            addCriterion("cust_addr_seq is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqIsNotNull() {
            addCriterion("cust_addr_seq is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqEqualTo(Short value) {
            addCriterion("cust_addr_seq =", value, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqNotEqualTo(Short value) {
            addCriterion("cust_addr_seq <>", value, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqGreaterThan(Short value) {
            addCriterion("cust_addr_seq >", value, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqGreaterThanOrEqualTo(Short value) {
            addCriterion("cust_addr_seq >=", value, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqLessThan(Short value) {
            addCriterion("cust_addr_seq <", value, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqLessThanOrEqualTo(Short value) {
            addCriterion("cust_addr_seq <=", value, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqIn(List<Short> values) {
            addCriterion("cust_addr_seq in", values, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqNotIn(List<Short> values) {
            addCriterion("cust_addr_seq not in", values, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqBetween(Short value1, Short value2) {
            addCriterion("cust_addr_seq between", value1, value2, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrSeqNotBetween(Short value1, Short value2) {
            addCriterion("cust_addr_seq not between", value1, value2, "custAddrSeq");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeIsNull() {
            addCriterion("cust_addr_type is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeIsNotNull() {
            addCriterion("cust_addr_type is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeEqualTo(String value) {
            addCriterion("cust_addr_type =", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeNotEqualTo(String value) {
            addCriterion("cust_addr_type <>", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeGreaterThan(String value) {
            addCriterion("cust_addr_type >", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cust_addr_type >=", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeLessThan(String value) {
            addCriterion("cust_addr_type <", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeLessThanOrEqualTo(String value) {
            addCriterion("cust_addr_type <=", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeLike(String value) {
            addCriterion("cust_addr_type like", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeNotLike(String value) {
            addCriterion("cust_addr_type not like", value, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeIn(List<String> values) {
            addCriterion("cust_addr_type in", values, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeNotIn(List<String> values) {
            addCriterion("cust_addr_type not in", values, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeBetween(String value1, String value2) {
            addCriterion("cust_addr_type between", value1, value2, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrTypeNotBetween(String value1, String value2) {
            addCriterion("cust_addr_type not between", value1, value2, "custAddrType");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdIsNull() {
            addCriterion("cust_addr_postcd is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdIsNotNull() {
            addCriterion("cust_addr_postcd is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdEqualTo(String value) {
            addCriterion("cust_addr_postcd =", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdNotEqualTo(String value) {
            addCriterion("cust_addr_postcd <>", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdGreaterThan(String value) {
            addCriterion("cust_addr_postcd >", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdGreaterThanOrEqualTo(String value) {
            addCriterion("cust_addr_postcd >=", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdLessThan(String value) {
            addCriterion("cust_addr_postcd <", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdLessThanOrEqualTo(String value) {
            addCriterion("cust_addr_postcd <=", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdLike(String value) {
            addCriterion("cust_addr_postcd like", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdNotLike(String value) {
            addCriterion("cust_addr_postcd not like", value, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdIn(List<String> values) {
            addCriterion("cust_addr_postcd in", values, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdNotIn(List<String> values) {
            addCriterion("cust_addr_postcd not in", values, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdBetween(String value1, String value2) {
            addCriterion("cust_addr_postcd between", value1, value2, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPostcdNotBetween(String value1, String value2) {
            addCriterion("cust_addr_postcd not between", value1, value2, "custAddrPostcd");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefIsNull() {
            addCriterion("cust_addr_pref is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefIsNotNull() {
            addCriterion("cust_addr_pref is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefEqualTo(String value) {
            addCriterion("cust_addr_pref =", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefNotEqualTo(String value) {
            addCriterion("cust_addr_pref <>", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefGreaterThan(String value) {
            addCriterion("cust_addr_pref >", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefGreaterThanOrEqualTo(String value) {
            addCriterion("cust_addr_pref >=", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefLessThan(String value) {
            addCriterion("cust_addr_pref <", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefLessThanOrEqualTo(String value) {
            addCriterion("cust_addr_pref <=", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefLike(String value) {
            addCriterion("cust_addr_pref like", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefNotLike(String value) {
            addCriterion("cust_addr_pref not like", value, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefIn(List<String> values) {
            addCriterion("cust_addr_pref in", values, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefNotIn(List<String> values) {
            addCriterion("cust_addr_pref not in", values, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefBetween(String value1, String value2) {
            addCriterion("cust_addr_pref between", value1, value2, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrPrefNotBetween(String value1, String value2) {
            addCriterion("cust_addr_pref not between", value1, value2, "custAddrPref");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityIsNull() {
            addCriterion("cust_addr_city is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityIsNotNull() {
            addCriterion("cust_addr_city is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityEqualTo(String value) {
            addCriterion("cust_addr_city =", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityNotEqualTo(String value) {
            addCriterion("cust_addr_city <>", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityGreaterThan(String value) {
            addCriterion("cust_addr_city >", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityGreaterThanOrEqualTo(String value) {
            addCriterion("cust_addr_city >=", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityLessThan(String value) {
            addCriterion("cust_addr_city <", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityLessThanOrEqualTo(String value) {
            addCriterion("cust_addr_city <=", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityLike(String value) {
            addCriterion("cust_addr_city like", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityNotLike(String value) {
            addCriterion("cust_addr_city not like", value, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityIn(List<String> values) {
            addCriterion("cust_addr_city in", values, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityNotIn(List<String> values) {
            addCriterion("cust_addr_city not in", values, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityBetween(String value1, String value2) {
            addCriterion("cust_addr_city between", value1, value2, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrCityNotBetween(String value1, String value2) {
            addCriterion("cust_addr_city not between", value1, value2, "custAddrCity");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetIsNull() {
            addCriterion("cust_addr_steet is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetIsNotNull() {
            addCriterion("cust_addr_steet is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetEqualTo(String value) {
            addCriterion("cust_addr_steet =", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetNotEqualTo(String value) {
            addCriterion("cust_addr_steet <>", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetGreaterThan(String value) {
            addCriterion("cust_addr_steet >", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetGreaterThanOrEqualTo(String value) {
            addCriterion("cust_addr_steet >=", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetLessThan(String value) {
            addCriterion("cust_addr_steet <", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetLessThanOrEqualTo(String value) {
            addCriterion("cust_addr_steet <=", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetLike(String value) {
            addCriterion("cust_addr_steet like", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetNotLike(String value) {
            addCriterion("cust_addr_steet not like", value, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetIn(List<String> values) {
            addCriterion("cust_addr_steet in", values, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetNotIn(List<String> values) {
            addCriterion("cust_addr_steet not in", values, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetBetween(String value1, String value2) {
            addCriterion("cust_addr_steet between", value1, value2, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrSteetNotBetween(String value1, String value2) {
            addCriterion("cust_addr_steet not between", value1, value2, "custAddrSteet");
            return (Criteria) this;
        }

        public Criteria andCustAddrManIsNull() {
            addCriterion("cust_addr_man is null");
            return (Criteria) this;
        }

        public Criteria andCustAddrManIsNotNull() {
            addCriterion("cust_addr_man is not null");
            return (Criteria) this;
        }

        public Criteria andCustAddrManEqualTo(String value) {
            addCriterion("cust_addr_man =", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManNotEqualTo(String value) {
            addCriterion("cust_addr_man <>", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManGreaterThan(String value) {
            addCriterion("cust_addr_man >", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManGreaterThanOrEqualTo(String value) {
            addCriterion("cust_addr_man >=", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManLessThan(String value) {
            addCriterion("cust_addr_man <", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManLessThanOrEqualTo(String value) {
            addCriterion("cust_addr_man <=", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManLike(String value) {
            addCriterion("cust_addr_man like", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManNotLike(String value) {
            addCriterion("cust_addr_man not like", value, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManIn(List<String> values) {
            addCriterion("cust_addr_man in", values, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManNotIn(List<String> values) {
            addCriterion("cust_addr_man not in", values, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManBetween(String value1, String value2) {
            addCriterion("cust_addr_man between", value1, value2, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCustAddrManNotBetween(String value1, String value2) {
            addCriterion("cust_addr_man not between", value1, value2, "custAddrMan");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cust_addr
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}