package net.newbiz.ebil.billing.dao.model;

import java.util.Date;

public class TCust extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_cd
     *
     * @mbggenerated
     */
    private Integer custCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_nm
     *
     * @mbggenerated
     */
    private String custNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_kana
     *
     * @mbggenerated
     */
    private String custKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_sex
     *
     * @mbggenerated
     */
    private Short custSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_type
     *
     * @mbggenerated
     */
    private Short custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_telno
     *
     * @mbggenerated
     */
    private String custTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_mob_telno
     *
     * @mbggenerated
     */
    private String custMobTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.cust_mail_addr
     *
     * @mbggenerated
     */
    private String custMailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.sys_state_cd
     *
     * @mbggenerated
     */
    private Short sysStateCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_cd
     *
     * @return the value of t_cust.cust_cd
     *
     * @mbggenerated
     */
    public Integer getCustCd() {
        return custCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_cd
     *
     * @param custCd the value for t_cust.cust_cd
     *
     * @mbggenerated
     */
    public void setCustCd(Integer custCd) {
        this.custCd = custCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_nm
     *
     * @return the value of t_cust.cust_nm
     *
     * @mbggenerated
     */
    public String getCustNm() {
        return custNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_nm
     *
     * @param custNm the value for t_cust.cust_nm
     *
     * @mbggenerated
     */
    public void setCustNm(String custNm) {
        this.custNm = custNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_kana
     *
     * @return the value of t_cust.cust_kana
     *
     * @mbggenerated
     */
    public String getCustKana() {
        return custKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_kana
     *
     * @param custKana the value for t_cust.cust_kana
     *
     * @mbggenerated
     */
    public void setCustKana(String custKana) {
        this.custKana = custKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_sex
     *
     * @return the value of t_cust.cust_sex
     *
     * @mbggenerated
     */
    public Short getCustSex() {
        return custSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_sex
     *
     * @param custSex the value for t_cust.cust_sex
     *
     * @mbggenerated
     */
    public void setCustSex(Short custSex) {
        this.custSex = custSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_type
     *
     * @return the value of t_cust.cust_type
     *
     * @mbggenerated
     */
    public Short getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_type
     *
     * @param custType the value for t_cust.cust_type
     *
     * @mbggenerated
     */
    public void setCustType(Short custType) {
        this.custType = custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_telno
     *
     * @return the value of t_cust.cust_telno
     *
     * @mbggenerated
     */
    public String getCustTelno() {
        return custTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_telno
     *
     * @param custTelno the value for t_cust.cust_telno
     *
     * @mbggenerated
     */
    public void setCustTelno(String custTelno) {
        this.custTelno = custTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_mob_telno
     *
     * @return the value of t_cust.cust_mob_telno
     *
     * @mbggenerated
     */
    public String getCustMobTelno() {
        return custMobTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_mob_telno
     *
     * @param custMobTelno the value for t_cust.cust_mob_telno
     *
     * @mbggenerated
     */
    public void setCustMobTelno(String custMobTelno) {
        this.custMobTelno = custMobTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.cust_mail_addr
     *
     * @return the value of t_cust.cust_mail_addr
     *
     * @mbggenerated
     */
    public String getCustMailAddr() {
        return custMailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.cust_mail_addr
     *
     * @param custMailAddr the value for t_cust.cust_mail_addr
     *
     * @mbggenerated
     */
    public void setCustMailAddr(String custMailAddr) {
        this.custMailAddr = custMailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.sys_state_cd
     *
     * @return the value of t_cust.sys_state_cd
     *
     * @mbggenerated
     */
    public Short getSysStateCd() {
        return sysStateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.sys_state_cd
     *
     * @param sysStateCd the value for t_cust.sys_state_cd
     *
     * @mbggenerated
     */
    public void setSysStateCd(Short sysStateCd) {
        this.sysStateCd = sysStateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.creater
     *
     * @return the value of t_cust.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.creater
     *
     * @param creater the value for t_cust.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.create_timestamp
     *
     * @return the value of t_cust.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.create_timestamp
     *
     * @param createTimestamp the value for t_cust.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.updater
     *
     * @return the value of t_cust.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.updater
     *
     * @param updater the value for t_cust.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust.update_timestamp
     *
     * @return the value of t_cust.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust.update_timestamp
     *
     * @param updateTimestamp the value for t_cust.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}