package net.newbiz.ebil.billing.dao.model;

public class TCustPayLinkKey extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_pay_link.cust_cd
     *
     * @mbggenerated
     */
    private Integer custCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cust_pay_link.pay_no
     *
     * @mbggenerated
     */
    private Long payNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_pay_link.cust_cd
     *
     * @return the value of t_cust_pay_link.cust_cd
     *
     * @mbggenerated
     */
    public Integer getCustCd() {
        return custCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_pay_link.cust_cd
     *
     * @param custCd the value for t_cust_pay_link.cust_cd
     *
     * @mbggenerated
     */
    public void setCustCd(Integer custCd) {
        this.custCd = custCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cust_pay_link.pay_no
     *
     * @return the value of t_cust_pay_link.pay_no
     *
     * @mbggenerated
     */
    public Long getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cust_pay_link.pay_no
     *
     * @param payNo the value for t_cust_pay_link.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(Long payNo) {
        this.payNo = payNo;
    }
}