package net.newbiz.ebil.billing.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TPaySubCvsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public TPaySubCvsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPayNoIsNull() {
            addCriterion("pay_no is null");
            return (Criteria) this;
        }

        public Criteria andPayNoIsNotNull() {
            addCriterion("pay_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayNoEqualTo(Long value) {
            addCriterion("pay_no =", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoNotEqualTo(Long value) {
            addCriterion("pay_no <>", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoGreaterThan(Long value) {
            addCriterion("pay_no >", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_no >=", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoLessThan(Long value) {
            addCriterion("pay_no <", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoLessThanOrEqualTo(Long value) {
            addCriterion("pay_no <=", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoIn(List<Long> values) {
            addCriterion("pay_no in", values, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoNotIn(List<Long> values) {
            addCriterion("pay_no not in", values, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoBetween(Long value1, Long value2) {
            addCriterion("pay_no between", value1, value2, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoNotBetween(Long value1, Long value2) {
            addCriterion("pay_no not between", value1, value2, "payNo");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdIsNull() {
            addCriterion("cvs_corp_id is null");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdIsNotNull() {
            addCriterion("cvs_corp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdEqualTo(String value) {
            addCriterion("cvs_corp_id =", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdNotEqualTo(String value) {
            addCriterion("cvs_corp_id <>", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdGreaterThan(String value) {
            addCriterion("cvs_corp_id >", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdGreaterThanOrEqualTo(String value) {
            addCriterion("cvs_corp_id >=", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdLessThan(String value) {
            addCriterion("cvs_corp_id <", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdLessThanOrEqualTo(String value) {
            addCriterion("cvs_corp_id <=", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdLike(String value) {
            addCriterion("cvs_corp_id like", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdNotLike(String value) {
            addCriterion("cvs_corp_id not like", value, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdIn(List<String> values) {
            addCriterion("cvs_corp_id in", values, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdNotIn(List<String> values) {
            addCriterion("cvs_corp_id not in", values, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdBetween(String value1, String value2) {
            addCriterion("cvs_corp_id between", value1, value2, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsCorpIdNotBetween(String value1, String value2) {
            addCriterion("cvs_corp_id not between", value1, value2, "cvsCorpId");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoIsNull() {
            addCriterion("cvs_branch_no is null");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoIsNotNull() {
            addCriterion("cvs_branch_no is not null");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoEqualTo(String value) {
            addCriterion("cvs_branch_no =", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoNotEqualTo(String value) {
            addCriterion("cvs_branch_no <>", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoGreaterThan(String value) {
            addCriterion("cvs_branch_no >", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoGreaterThanOrEqualTo(String value) {
            addCriterion("cvs_branch_no >=", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoLessThan(String value) {
            addCriterion("cvs_branch_no <", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoLessThanOrEqualTo(String value) {
            addCriterion("cvs_branch_no <=", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoLike(String value) {
            addCriterion("cvs_branch_no like", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoNotLike(String value) {
            addCriterion("cvs_branch_no not like", value, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoIn(List<String> values) {
            addCriterion("cvs_branch_no in", values, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoNotIn(List<String> values) {
            addCriterion("cvs_branch_no not in", values, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoBetween(String value1, String value2) {
            addCriterion("cvs_branch_no between", value1, value2, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCvsBranchNoNotBetween(String value1, String value2) {
            addCriterion("cvs_branch_no not between", value1, value2, "cvsBranchNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoIsNull() {
            addCriterion("csv_no is null");
            return (Criteria) this;
        }

        public Criteria andCsvNoIsNotNull() {
            addCriterion("csv_no is not null");
            return (Criteria) this;
        }

        public Criteria andCsvNoEqualTo(String value) {
            addCriterion("csv_no =", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoNotEqualTo(String value) {
            addCriterion("csv_no <>", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoGreaterThan(String value) {
            addCriterion("csv_no >", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoGreaterThanOrEqualTo(String value) {
            addCriterion("csv_no >=", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoLessThan(String value) {
            addCriterion("csv_no <", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoLessThanOrEqualTo(String value) {
            addCriterion("csv_no <=", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoLike(String value) {
            addCriterion("csv_no like", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoNotLike(String value) {
            addCriterion("csv_no not like", value, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoIn(List<String> values) {
            addCriterion("csv_no in", values, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoNotIn(List<String> values) {
            addCriterion("csv_no not in", values, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoBetween(String value1, String value2) {
            addCriterion("csv_no between", value1, value2, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCsvNoNotBetween(String value1, String value2) {
            addCriterion("csv_no not between", value1, value2, "csvNo");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}