package net.newbiz.ebil.billing.dao.model;

import java.util.Date;

public class TPaySubCvs extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.pay_no
     *
     * @mbggenerated
     */
    private Long payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.cvs_corp_id
     *
     * @mbggenerated
     */
    private String cvsCorpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.cvs_branch_no
     *
     * @mbggenerated
     */
    private String cvsBranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.csv_no
     *
     * @mbggenerated
     */
    private String csvNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sub_cvs.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.pay_no
     *
     * @return the value of t_pay_sub_cvs.pay_no
     *
     * @mbggenerated
     */
    public Long getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.pay_no
     *
     * @param payNo the value for t_pay_sub_cvs.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(Long payNo) {
        this.payNo = payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.cvs_corp_id
     *
     * @return the value of t_pay_sub_cvs.cvs_corp_id
     *
     * @mbggenerated
     */
    public String getCvsCorpId() {
        return cvsCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.cvs_corp_id
     *
     * @param cvsCorpId the value for t_pay_sub_cvs.cvs_corp_id
     *
     * @mbggenerated
     */
    public void setCvsCorpId(String cvsCorpId) {
        this.cvsCorpId = cvsCorpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.cvs_branch_no
     *
     * @return the value of t_pay_sub_cvs.cvs_branch_no
     *
     * @mbggenerated
     */
    public String getCvsBranchNo() {
        return cvsBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.cvs_branch_no
     *
     * @param cvsBranchNo the value for t_pay_sub_cvs.cvs_branch_no
     *
     * @mbggenerated
     */
    public void setCvsBranchNo(String cvsBranchNo) {
        this.cvsBranchNo = cvsBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.csv_no
     *
     * @return the value of t_pay_sub_cvs.csv_no
     *
     * @mbggenerated
     */
    public String getCsvNo() {
        return csvNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.csv_no
     *
     * @param csvNo the value for t_pay_sub_cvs.csv_no
     *
     * @mbggenerated
     */
    public void setCsvNo(String csvNo) {
        this.csvNo = csvNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.creater
     *
     * @return the value of t_pay_sub_cvs.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.creater
     *
     * @param creater the value for t_pay_sub_cvs.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.create_timestamp
     *
     * @return the value of t_pay_sub_cvs.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.create_timestamp
     *
     * @param createTimestamp the value for t_pay_sub_cvs.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.updater
     *
     * @return the value of t_pay_sub_cvs.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.updater
     *
     * @param updater the value for t_pay_sub_cvs.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sub_cvs.update_timestamp
     *
     * @return the value of t_pay_sub_cvs.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sub_cvs.update_timestamp
     *
     * @param updateTimestamp the value for t_pay_sub_cvs.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}