package net.newbiz.ebil.billing.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSetoffHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public TSetoffHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSetoffNoIsNull() {
            addCriterion("setoff_no is null");
            return (Criteria) this;
        }

        public Criteria andSetoffNoIsNotNull() {
            addCriterion("setoff_no is not null");
            return (Criteria) this;
        }

        public Criteria andSetoffNoEqualTo(Long value) {
            addCriterion("setoff_no =", value, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoNotEqualTo(Long value) {
            addCriterion("setoff_no <>", value, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoGreaterThan(Long value) {
            addCriterion("setoff_no >", value, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoGreaterThanOrEqualTo(Long value) {
            addCriterion("setoff_no >=", value, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoLessThan(Long value) {
            addCriterion("setoff_no <", value, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoLessThanOrEqualTo(Long value) {
            addCriterion("setoff_no <=", value, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoIn(List<Long> values) {
            addCriterion("setoff_no in", values, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoNotIn(List<Long> values) {
            addCriterion("setoff_no not in", values, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoBetween(Long value1, Long value2) {
            addCriterion("setoff_no between", value1, value2, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andSetoffNoNotBetween(Long value1, Long value2) {
            addCriterion("setoff_no not between", value1, value2, "setoffNo");
            return (Criteria) this;
        }

        public Criteria andProcYmIsNull() {
            addCriterion("proc_ym is null");
            return (Criteria) this;
        }

        public Criteria andProcYmIsNotNull() {
            addCriterion("proc_ym is not null");
            return (Criteria) this;
        }

        public Criteria andProcYmEqualTo(String value) {
            addCriterion("proc_ym =", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmNotEqualTo(String value) {
            addCriterion("proc_ym <>", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmGreaterThan(String value) {
            addCriterion("proc_ym >", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmGreaterThanOrEqualTo(String value) {
            addCriterion("proc_ym >=", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmLessThan(String value) {
            addCriterion("proc_ym <", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmLessThanOrEqualTo(String value) {
            addCriterion("proc_ym <=", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmLike(String value) {
            addCriterion("proc_ym like", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmNotLike(String value) {
            addCriterion("proc_ym not like", value, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmIn(List<String> values) {
            addCriterion("proc_ym in", values, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmNotIn(List<String> values) {
            addCriterion("proc_ym not in", values, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmBetween(String value1, String value2) {
            addCriterion("proc_ym between", value1, value2, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcYmNotBetween(String value1, String value2) {
            addCriterion("proc_ym not between", value1, value2, "procYm");
            return (Criteria) this;
        }

        public Criteria andProcDateIsNull() {
            addCriterion("proc_date is null");
            return (Criteria) this;
        }

        public Criteria andProcDateIsNotNull() {
            addCriterion("proc_date is not null");
            return (Criteria) this;
        }

        public Criteria andProcDateEqualTo(String value) {
            addCriterion("proc_date =", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateNotEqualTo(String value) {
            addCriterion("proc_date <>", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateGreaterThan(String value) {
            addCriterion("proc_date >", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateGreaterThanOrEqualTo(String value) {
            addCriterion("proc_date >=", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateLessThan(String value) {
            addCriterion("proc_date <", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateLessThanOrEqualTo(String value) {
            addCriterion("proc_date <=", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateLike(String value) {
            addCriterion("proc_date like", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateNotLike(String value) {
            addCriterion("proc_date not like", value, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateIn(List<String> values) {
            addCriterion("proc_date in", values, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateNotIn(List<String> values) {
            addCriterion("proc_date not in", values, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateBetween(String value1, String value2) {
            addCriterion("proc_date between", value1, value2, "procDate");
            return (Criteria) this;
        }

        public Criteria andProcDateNotBetween(String value1, String value2) {
            addCriterion("proc_date not between", value1, value2, "procDate");
            return (Criteria) this;
        }

        public Criteria andBillNoIsNull() {
            addCriterion("bill_no is null");
            return (Criteria) this;
        }

        public Criteria andBillNoIsNotNull() {
            addCriterion("bill_no is not null");
            return (Criteria) this;
        }

        public Criteria andBillNoEqualTo(Long value) {
            addCriterion("bill_no =", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotEqualTo(Long value) {
            addCriterion("bill_no <>", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoGreaterThan(Long value) {
            addCriterion("bill_no >", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoGreaterThanOrEqualTo(Long value) {
            addCriterion("bill_no >=", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoLessThan(Long value) {
            addCriterion("bill_no <", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoLessThanOrEqualTo(Long value) {
            addCriterion("bill_no <=", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoIn(List<Long> values) {
            addCriterion("bill_no in", values, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotIn(List<Long> values) {
            addCriterion("bill_no not in", values, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoBetween(Long value1, Long value2) {
            addCriterion("bill_no between", value1, value2, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotBetween(Long value1, Long value2) {
            addCriterion("bill_no not between", value1, value2, "billNo");
            return (Criteria) this;
        }

        public Criteria andPayNoIsNull() {
            addCriterion("pay_no is null");
            return (Criteria) this;
        }

        public Criteria andPayNoIsNotNull() {
            addCriterion("pay_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayNoEqualTo(Long value) {
            addCriterion("pay_no =", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoNotEqualTo(Long value) {
            addCriterion("pay_no <>", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoGreaterThan(Long value) {
            addCriterion("pay_no >", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_no >=", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoLessThan(Long value) {
            addCriterion("pay_no <", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoLessThanOrEqualTo(Long value) {
            addCriterion("pay_no <=", value, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoIn(List<Long> values) {
            addCriterion("pay_no in", values, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoNotIn(List<Long> values) {
            addCriterion("pay_no not in", values, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoBetween(Long value1, Long value2) {
            addCriterion("pay_no between", value1, value2, "payNo");
            return (Criteria) this;
        }

        public Criteria andPayNoNotBetween(Long value1, Long value2) {
            addCriterion("pay_no not between", value1, value2, "payNo");
            return (Criteria) this;
        }

        public Criteria andSysStateCdIsNull() {
            addCriterion("sys_state_cd is null");
            return (Criteria) this;
        }

        public Criteria andSysStateCdIsNotNull() {
            addCriterion("sys_state_cd is not null");
            return (Criteria) this;
        }

        public Criteria andSysStateCdEqualTo(Short value) {
            addCriterion("sys_state_cd =", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdNotEqualTo(Short value) {
            addCriterion("sys_state_cd <>", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdGreaterThan(Short value) {
            addCriterion("sys_state_cd >", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdGreaterThanOrEqualTo(Short value) {
            addCriterion("sys_state_cd >=", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdLessThan(Short value) {
            addCriterion("sys_state_cd <", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdLessThanOrEqualTo(Short value) {
            addCriterion("sys_state_cd <=", value, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdIn(List<Short> values) {
            addCriterion("sys_state_cd in", values, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdNotIn(List<Short> values) {
            addCriterion("sys_state_cd not in", values, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdBetween(Short value1, Short value2) {
            addCriterion("sys_state_cd between", value1, value2, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andSysStateCdNotBetween(Short value1, Short value2) {
            addCriterion("sys_state_cd not between", value1, value2, "sysStateCd");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("create_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("create_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("create_timestamp =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("create_timestamp <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("create_timestamp >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("create_timestamp >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("create_timestamp <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("create_timestamp <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("create_timestamp in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("create_timestamp not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("create_timestamp between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("create_timestamp not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("update_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("update_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("update_timestamp =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("update_timestamp <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("update_timestamp >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("update_timestamp >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("update_timestamp <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("update_timestamp <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("update_timestamp in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("update_timestamp not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_setoff_history
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_setoff_history
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}