package net.newbiz.ebil.billing.dao.model;

import java.util.Date;

public class TSetoffHistory extends DtoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.setoff_no
     *
     * @mbggenerated
     */
    private Long setoffNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.proc_ym
     *
     * @mbggenerated
     */
    private String procYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.proc_date
     *
     * @mbggenerated
     */
    private String procDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.bill_no
     *
     * @mbggenerated
     */
    private Long billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.pay_no
     *
     * @mbggenerated
     */
    private Long payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.sys_state_cd
     *
     * @mbggenerated
     */
    private Short sysStateCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setoff_history.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.setoff_no
     *
     * @return the value of t_setoff_history.setoff_no
     *
     * @mbggenerated
     */
    public Long getSetoffNo() {
        return setoffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.setoff_no
     *
     * @param setoffNo the value for t_setoff_history.setoff_no
     *
     * @mbggenerated
     */
    public void setSetoffNo(Long setoffNo) {
        this.setoffNo = setoffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.proc_ym
     *
     * @return the value of t_setoff_history.proc_ym
     *
     * @mbggenerated
     */
    public String getProcYm() {
        return procYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.proc_ym
     *
     * @param procYm the value for t_setoff_history.proc_ym
     *
     * @mbggenerated
     */
    public void setProcYm(String procYm) {
        this.procYm = procYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.proc_date
     *
     * @return the value of t_setoff_history.proc_date
     *
     * @mbggenerated
     */
    public String getProcDate() {
        return procDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.proc_date
     *
     * @param procDate the value for t_setoff_history.proc_date
     *
     * @mbggenerated
     */
    public void setProcDate(String procDate) {
        this.procDate = procDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.bill_no
     *
     * @return the value of t_setoff_history.bill_no
     *
     * @mbggenerated
     */
    public Long getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.bill_no
     *
     * @param billNo the value for t_setoff_history.bill_no
     *
     * @mbggenerated
     */
    public void setBillNo(Long billNo) {
        this.billNo = billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.pay_no
     *
     * @return the value of t_setoff_history.pay_no
     *
     * @mbggenerated
     */
    public Long getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.pay_no
     *
     * @param payNo the value for t_setoff_history.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(Long payNo) {
        this.payNo = payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.sys_state_cd
     *
     * @return the value of t_setoff_history.sys_state_cd
     *
     * @mbggenerated
     */
    public Short getSysStateCd() {
        return sysStateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.sys_state_cd
     *
     * @param sysStateCd the value for t_setoff_history.sys_state_cd
     *
     * @mbggenerated
     */
    public void setSysStateCd(Short sysStateCd) {
        this.sysStateCd = sysStateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.creater
     *
     * @return the value of t_setoff_history.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.creater
     *
     * @param creater the value for t_setoff_history.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.create_timestamp
     *
     * @return the value of t_setoff_history.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.create_timestamp
     *
     * @param createTimestamp the value for t_setoff_history.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.updater
     *
     * @return the value of t_setoff_history.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.updater
     *
     * @param updater the value for t_setoff_history.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setoff_history.update_timestamp
     *
     * @return the value of t_setoff_history.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setoff_history.update_timestamp
     *
     * @param updateTimestamp the value for t_setoff_history.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}