package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.MPayway;
import net.newbiz.ebil.billing.dao.model.MPaywayExample;
import org.apache.ibatis.annotations.Param;

public interface MPaywayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int countByExample(MPaywayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int deleteByExample(MPaywayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String payTypeCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int insert(MPayway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int insertSelective(MPayway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    List<MPayway> selectByExample(MPaywayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    MPayway selectByPrimaryKey(String payTypeCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MPayway record, @Param("example") MPaywayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MPayway record, @Param("example") MPaywayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MPayway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_payway
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MPayway record);
}