package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TChgRsv;
import net.newbiz.ebil.billing.dao.model.TChgRsvExample;
import org.apache.ibatis.annotations.Param;

public interface TChgRsvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int countByExample(TChgRsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int deleteByExample(TChgRsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long chgRsvNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int insert(TChgRsv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int insertSelective(TChgRsv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    List<TChgRsv> selectByExample(TChgRsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    TChgRsv selectByPrimaryKey(Long chgRsvNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TChgRsv record, @Param("example") TChgRsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TChgRsv record, @Param("example") TChgRsvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TChgRsv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chg_rsv
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TChgRsv record);
}