package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TCustPayLink;
import net.newbiz.ebil.billing.dao.model.TCustPayLinkExample;
import net.newbiz.ebil.billing.dao.model.TCustPayLinkKey;
import org.apache.ibatis.annotations.Param;

public interface TCustPayLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int countByExample(TCustPayLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int deleteByExample(TCustPayLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TCustPayLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int insert(TCustPayLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int insertSelective(TCustPayLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    List<TCustPayLink> selectByExample(TCustPayLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    TCustPayLink selectByPrimaryKey(TCustPayLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TCustPayLink record, @Param("example") TCustPayLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TCustPayLink record, @Param("example") TCustPayLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCustPayLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_pay_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCustPayLink record);
}