package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TCustLink;
import net.newbiz.ebil.billing.dao.model.TCustLinkExample;
import net.newbiz.ebil.billing.dao.model.TCustLinkKey;
import org.apache.ibatis.annotations.Param;

public interface TCustLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int countByExample(TCustLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int deleteByExample(TCustLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TCustLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int insert(TCustLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int insertSelective(TCustLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    List<TCustLink> selectByExample(TCustLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    TCustLink selectByPrimaryKey(TCustLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TCustLink record, @Param("example") TCustLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TCustLink record, @Param("example") TCustLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCustLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCustLink record);
}