package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TCustAddr;
import net.newbiz.ebil.billing.dao.model.TCustAddrExample;
import net.newbiz.ebil.billing.dao.model.TCustAddrKey;
import org.apache.ibatis.annotations.Param;

public interface TCustAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int countByExample(TCustAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int deleteByExample(TCustAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TCustAddrKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int insert(TCustAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int insertSelective(TCustAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    List<TCustAddr> selectByExample(TCustAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    TCustAddr selectByPrimaryKey(TCustAddrKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TCustAddr record, @Param("example") TCustAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TCustAddr record, @Param("example") TCustAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCustAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust_addr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCustAddr record);
}