package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TCust;
import net.newbiz.ebil.billing.dao.model.TCustExample;
import org.apache.ibatis.annotations.Param;

public interface TCustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int countByExample(TCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int deleteByExample(TCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer custCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int insert(TCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int insertSelective(TCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    List<TCust> selectByExample(TCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    TCust selectByPrimaryKey(Integer custCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TCust record, @Param("example") TCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TCust record, @Param("example") TCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cust
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCust record);
}