package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TPay;
import net.newbiz.ebil.billing.dao.model.TPayExample;
import org.apache.ibatis.annotations.Param;

public interface TPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int countByExample(TPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int deleteByExample(TPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long payNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int insert(TPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int insertSelective(TPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    List<TPay> selectByExample(TPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    TPay selectByPrimaryKey(Long payNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TPay record, @Param("example") TPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TPay record, @Param("example") TPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPay record);
}