package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TPaySubCard;
import net.newbiz.ebil.billing.dao.model.TPaySubCardExample;
import org.apache.ibatis.annotations.Param;

public interface TPaySubCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int countByExample(TPaySubCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int deleteByExample(TPaySubCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long payNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int insert(TPaySubCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int insertSelective(TPaySubCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    List<TPaySubCard> selectByExample(TPaySubCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    TPaySubCard selectByPrimaryKey(Long payNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TPaySubCard record, @Param("example") TPaySubCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TPaySubCard record, @Param("example") TPaySubCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPaySubCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_card
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPaySubCard record);
}