package net.newbiz.ebil.billing.dao;

import java.util.List;
import net.newbiz.ebil.billing.dao.model.TPaySubCvs;
import net.newbiz.ebil.billing.dao.model.TPaySubCvsExample;
import org.apache.ibatis.annotations.Param;

public interface TPaySubCvsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int countByExample(TPaySubCvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int deleteByExample(TPaySubCvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long payNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int insert(TPaySubCvs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int insertSelective(TPaySubCvs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    List<TPaySubCvs> selectByExample(TPaySubCvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    TPaySubCvs selectByPrimaryKey(Long payNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TPaySubCvs record, @Param("example") TPaySubCvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TPaySubCvs record, @Param("example") TPaySubCvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPaySubCvs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sub_cvs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPaySubCvs record);
}